/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddressSearch {
    }
    interface MapComponent {
    }
    interface MapContainer {
    }
    interface PolygonEntry {
    }
}
declare global {
    interface HTMLAddressSearchElement extends Components.AddressSearch, HTMLStencilElement {
    }
    var HTMLAddressSearchElement: {
        prototype: HTMLAddressSearchElement;
        new (): HTMLAddressSearchElement;
    };
    interface HTMLMapComponentElement extends Components.MapComponent, HTMLStencilElement {
    }
    var HTMLMapComponentElement: {
        prototype: HTMLMapComponentElement;
        new (): HTMLMapComponentElement;
    };
    interface HTMLMapContainerElement extends Components.MapContainer, HTMLStencilElement {
    }
    var HTMLMapContainerElement: {
        prototype: HTMLMapContainerElement;
        new (): HTMLMapContainerElement;
    };
    interface HTMLPolygonEntryElement extends Components.PolygonEntry, HTMLStencilElement {
    }
    var HTMLPolygonEntryElement: {
        prototype: HTMLPolygonEntryElement;
        new (): HTMLPolygonEntryElement;
    };
    interface HTMLElementTagNameMap {
        "address-search": HTMLAddressSearchElement;
        "map-component": HTMLMapComponentElement;
        "map-container": HTMLMapContainerElement;
        "polygon-entry": HTMLPolygonEntryElement;
    }
}
declare namespace LocalJSX {
    interface AddressSearch {
    }
    interface MapComponent {
    }
    interface MapContainer {
    }
    interface PolygonEntry {
    }
    interface IntrinsicElements {
        "address-search": AddressSearch;
        "map-component": MapComponent;
        "map-container": MapContainer;
        "polygon-entry": PolygonEntry;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "address-search": LocalJSX.AddressSearch & JSXBase.HTMLAttributes<HTMLAddressSearchElement>;
            "map-component": LocalJSX.MapComponent & JSXBase.HTMLAttributes<HTMLMapComponentElement>;
            "map-container": LocalJSX.MapContainer & JSXBase.HTMLAttributes<HTMLMapContainerElement>;
            "polygon-entry": LocalJSX.PolygonEntry & JSXBase.HTMLAttributes<HTMLPolygonEntryElement>;
        }
    }
}
